#Based on PixelGamesToDiscord Plugin config file!
#BanSystem with Discord Integration config file!

#settings
settings:
  #plugin prefix
  #default: "§l§eBanSystem §r§7|> §r "
  prefix: "§l§eBanSystem §r§7|> §r "

  #webhook name on discord
  name: "Advanced BanSystem"

  #here are the messages
  messages:
    #syntax of message wich sent by /discord command
    #{suspect} will be replaced with ur ingame name
    #{reason} will be replaced with ur chat message
    report: "The Player {suspect} has been banned for {reason}!"
  #you can add more than just one link!
  webhooks:
    - "webhook link 1"
    - "webhook link 2" #...

  #enable/disable message sending to discord
  #default: true
  enabled: true
